"Let's hope is working"

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -22,13 +22,7 @@ jobs:
         run: |
           pip install --upgrade pip
           pip install flake8
-      
-      - name: Run pip-audit (Log Findings, Don’t Fail)
-        continue-on-error: true
-        run: pip-audit -v || true
-
-      - name: Analyze dependencies for vulnerabilities
-        run: pip install pip-audit
+          flake8 .
       
       - name: Run pip-audit (Log Findings, Don’t Fail)
         continue-on-error: true
@@ -45,19 +39,33 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
-      - name: Build docker Image
-        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/develop:develop -f saleor-api/Dockerfile saleor-api/
+      - name: Build docker-api Image
+        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/saleor-api:develop -f saleor-api/Dockerfile saleor-api
 
-      - name: Run Health Check (Accept 200 or 404)
+      - name: Build Docker Image for saleor-dashboard
+        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/saleor-dashboard:develop -f saleor-dashboard/Dockerfile saleor-dashboard
+  
+      - name: Run Health Check for API(Accept 200 or 404)
         run: |
-          docker run -d --name temp_container -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/develop:develop
+          docker run --rm -d --name temp_api -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/saleor-api:develop 
           sleep 10
           if curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/graphql | grep -qE "200|404"; then
-            echo "✅ Health Check Passed"
+            echo " API Health Check Passed"
           else
-            echo "❌ Health Check Failed" && exit 1
+            echo " Health Check Failed" && exit 1
           fi
-          docker stop temp_container && docker rm temp_container
+          docker stop temp_api && docker rm temp_api
+
+      - name: Run Health Check for Dashboard(Accept 200 or 404)
+        run: |
+          docker run --rm -d --name temp_dashboard -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/saleor-dashboard:develop 
+          sleep 10
+          if curl -s -o /dev/null -w "%{http_code}" http://localhost:3000 | grep -qE "200|404"; then
+            echo " Dashboard Health Check Passed"
+          else
+            echo " Health Check Failed" && exit 1
+          fi
+          docker stop temp_dashboard && docker rm temp_dashboard
 
       - name: Install Trivy
         run: |
@@ -65,19 +73,29 @@ jobs:
           sudo apt-get install -y wget
           wget -qO - https://aquasecurity.github.io/trivy/releases/latest/install.sh | sudo bash          
 
-          - name: Trivy Vulnerability 
-          run: |
-            trivy image ${{ secrets.DOCKER_USERNAME }}/saleor-api:develop | tee trivy_log.txt || true
+      - name: Trivy Vulnerability Scan (API)
+        continue-on-error: true
+        run: |
+          trivy image ${{ secrets.DOCKER_USERNAME }}/saleor-api:develop | tee trivy_api_log.txt || true
   
+      - name: Trivy Vulnerability Scan (Dashboard)
+        continue-on-error: true
+        run: |
+          trivy image ${{ secrets.DOCKER_USERNAME }}/saleor-dashboard:develop | tee trivy_dashboard_log.txt || true
+      
       - name: Upload Trivy Log
         uses: actions/upload-artifact@v4
         with:
-            name: trivy-develop-log
-            path: trivy_log.txt
-
+            name: trivy-logs
+            path: |
+              trivy_api_log.txt
+              trivy_dashboard_log.txt
 
       - name: Login to DockerHub
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
 
-      - name: Docker push Image
-        run: docker push ${{ secrets.DOCKER_USERNAME }}/develop:develop
+      - name: Push Api Image to DockerHub
+        run: docker push ${{ secrets.DOCKER_USERNAME }}/saleor-api:develop
+
+      - name: Push Dashboard Image to DockerHub
+        run: docker push ${{ secrets.DOCKER_USERNAME }}/saleor-dashboard:develop
